### PR TITLE
Add templates for autoupgrade tests

### PR DESCRIPTION
**Pull request by Quetzacoalt91**

### CODE REVIEW

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hello, please update the Readme to explain how to get the git submodule

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hello, please update the Readme to explain how to get the git submodule

**Comment by jolelievre** [comment]
Hi @Quetzacoalt91 I'm not sure I understand everything about this PR
The purpose is to have prepared docker that you can run with the autoupgrade module installed?

Then I'm wondering (as in my forst comment), the autoupgrade won't be present unless you init and install submodules right?
And second although the module is shared with the container there is no need for an instruction to install it?

**Comment by PierreRambaud** [comment]
Hi @Quetzacoalt91 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
